[project]
name = "hf-learning-journey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.1.0",
    "datasets>=5.1.0",
    "huggingface-hub>=1.5.0,<2.0",
    "torch>=2.14.1",
    "transformers>=5.19.0",
]

[project.scripts]
hf-learning-journey = "hf_learning_journey:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
